/** alias_normalized → canonical display name */
export const ALIAS_MAP: Record<string, string> = {
  // Pondicherry / Puducherry
  'pondy':            'Puducherry',
  'pondicherry':      'Puducherry',
  'pudu':             'Puducherry',
  'puducherry':       'Puducherry',
  'pondycherry':      'Puducherry',

  // Tamil Nadu cities
  'trichy':           'Tiruchirappalli',
  'tiruchy':          'Tiruchirappalli',
  'trichinopoly':     'Tiruchirappalli',
  'tiruchirappalli':  'Tiruchirappalli',
  'thirchy':          'Tiruchirappalli',
  'madurai':          'Madurai',
  'coimbatore':       'Coimbatore',
  'cbe':              'Coimbatore',
  'kovai':            'Coimbatore',
  'salem':            'Salem',
  'erode':            'Erode',
  'tirunelveli':      'Tirunelveli',
  'tirunelvelly':     'Tirunelveli',
  'nellai':           'Tirunelveli',
  'vellore':          'Vellore',
  'thanjavur':        'Thanjavur',
  'tanjore':          'Thanjavur',
  'chengalpattu':     'Chengalpattu',
  'chengalpet':       'Chengalpattu',
  'kancheepuram':     'Kanchipuram',
  'kanchi':           'Kanchipuram',
  'kanchipuram':      'Kanchipuram',
  'villupuram':       'Villupuram',
  'villipuram':       'Villupuram',
  'vilupuram':        'Villupuram',
  'cuddalore':        'Cuddalore',
  'cudalore':         'Cuddalore',
  'kumbakonam':       'Kumbakonam',
  'kumbakonum':       'Kumbakonam',
  'nagapattinam':     'Nagapattinam',
  'nagapatinam':      'Nagapattinam',
  'dindigul':         'Dindigul',
  'dindugal':         'Dindigul',
  'tiruppur':         'Tiruppur',
  'tirupur':          'Tiruppur',
  'hosur':            'Hosur',
  'krishnagiri':      'Krishnagiri',
  'dharmapuri':       'Dharmapuri',
  'namakkal':         'Namakkal',
  'karur':            'Karur',
  'perambalur':       'Perambalur',
  'ariyalur':         'Ariyalur',
  'sivaganga':        'Sivaganga',
  'virudhunagar':     'Virudhunagar',
  'ramanathapuram':   'Ramanathapuram',
  'thoothukudi':      'Thoothukudi',
  'tuticorin':        'Thoothukudi',
  'kanyakumari':      'Kanyakumari',
  'nagercoil':        'Nagercoil',

  // Chennai localities
  'tnagar':           'T. Nagar',
  'tnagr':            'T. Nagar',
  'thyagarayanagar':  'T. Nagar',
  'mylapore':         'Mylapore',
  'velachery':        'Velachery',
  'velacherri':       'Velachery',
  'velacheri':        'Velachery',
  'adyar':            'Adyar',
  'annanagar':        'Anna Nagar',
  'annanagr':         'Anna Nagar',
  'chennai':          'Chennai',
  'madras':           'Chennai',
  'tambaram':         'Tambaram',
  'chrompet':         'Chromepet',
  'chromepet':        'Chromepet',
  'perambur':         'Perambur',
  'ambattur':         'Ambattur',
  'avadi':            'Avadi',
  'porur':            'Porur',
  'guindy':           'Guindy',
  'kodambakkam':      'Kodambakkam',
  'nungambakkam':     'Nungambakkam',
  'egmore':           'Egmore',
  'royapettah':       'Royapettah',
  'triplicane':       'Triplicane',
  'tondiarpet':       'Tondiarpet',
  'washermanpet':     'Washermanpet',
  'thiruvottiyur':    'Thiruvottiyur',
  'sholinganallur':   'Sholinganallur',
  'perungudi':        'Perungudi',
  'thoraipakkam':     'Thoraipakkam',
  'pallikaranai':     'Pallikaranai',
  'medavakkam':       'Medavakkam',
  'madipakkam':       'Madipakkam',
  'nanganallur':      'Nanganallur',
  'alandur':          'Alandur',
  'saidapet':         'Saidapet',
  'kotturpuram':      'Kotturpuram',
  'besantnagar':      'Besant Nagar',
  'besanthnagar':     'Besant Nagar',
  'besant nagar':     'Besant Nagar',
  

  // Tamil Nadu
  'tamil nadu':                        'Tamil Nadu',
  'tamilnadu':                         'Tamil Nadu',
  'tamilnad':                          'Tamil Nadu',
  'tamil nad':                         'Tamil Nadu',
  'tamilnadhu':                        'Tamil Nadu',
  'tamilnattu':                        'Tamil Nadu',
  'tamilnatu':                         'Tamil Nadu',
  'tamilnado':                         'Tamil Nadu',
  'tn':                                'Tamil Nadu',
  't.n':                               'Tamil Nadu',
  't.n.':                              'Tamil Nadu',
  'tamin nadu':                        'Tamil Nadu',
  'tamizh nadu':                       'Tamil Nadu',
  'tamizhnadu':                        'Tamil Nadu',
  'tamiznadu':                         'Tamil Nadu',
  'tamiznad':                          'Tamil Nadu',
  'thamizh nadu':                      'Tamil Nadu',
  'thamizhnadhu':                      'Tamil Nadu',
  'thamizhnad':                        'Tamil Nadu',

  // Puducherry
  'ponducherry':                       'Puducherry',
  'puduchery':                         'Puducherry',
  'pondichery':                        'Puducherry',
  'ponduchery':                        'Puducherry',
  'puducherry ut':                     'Puducherry',
  'pondicherry ut':                    'Puducherry',
  'pudducherry':                       'Puducherry',
  'pudduchery':                        'Puducherry',
  'puddu':                             'Puducherry',
  'pudhucherry':                       'Puducherry',
  'pudhuchery':                        'Puducherry',
  'pudhu':                             'Puducherry',
  'puthucherry':                       'Puducherry',
  'puthuchery':                        'Puducherry',
  'puthu':                             'Puducherry',
  'puduche':                           'Puducherry',

  // Chennai
  'chenai':                            'Chennai',
  'chennaai':                          'Chennai',
  'chinnai':                           'Chennai',
  'chenni':                            'Chennai',
  'madras city':                       'Chennai',
  'madurais':                          'Chennai',
  'chenaai':                           'Chennai',
  'chennay':                           'Chennai',
  'cheennai':                          'Chennai',

  // Tiruchirappalli
  'trichirappalli':                    'Tiruchirappalli',
  'tirchirappalli':                    'Tiruchirappalli',
  'tiruchirrapalli':                   'Tiruchirappalli',
  'tiruchirappali':                    'Tiruchirappalli',
  'tiruchirrapali':                    'Tiruchirappalli',
  'tiruchirapalli':                    'Tiruchirappalli',
  'tiruchirapali':                     'Tiruchirappalli',
  'trichirapalli':                     'Tiruchirappalli',
  'trichirrapalli':                    'Tiruchirappalli',
  'trichrappalli':                     'Tiruchirappalli',
  'trichirapali':                      'Tiruchirappalli',
  'tiruchhi':                          'Tiruchirappalli',
  'tirucci':                           'Tiruchirappalli',
  'tiruchi':                           'Tiruchirappalli',
  'trisur':                            'Tiruchirappalli',

  // Madurai
  'madurei':                           'Madurai',
  'madurai dt':                        'Madurai',
  'madura':                            'Madurai',
  'maduai':                            'Madurai',
  'maduraii':                          'Madurai',
  'maadurai':                          'Madurai',
  'madure':                            'Madurai',
  'maduraa':                           'Madurai',

  // Coimbatore
  'coimbatur':                         'Coimbatore',
  'coimbatoor':                        'Coimbatore',
  'coimbatour':                        'Coimbatore',
  'coimbator':                         'Coimbatore',
  'coimbatorre':                       'Coimbatore',
  'koyamuthur':                        'Coimbatore',
  'koyamuttur':                        'Coimbatore',
  'koimbatore':                        'Coimbatore',
  'koimbatur':                         'Coimbatore',
  'covai':                             'Coimbatore',
  'kombatore':                         'Coimbatore',
  'comibatore':                        'Coimbatore',
  'coimbtore':                         'Coimbatore',
  'coimbtaore':                        'Coimbatore',
  'coinbatore':                        'Coimbatore',

  // Salem
  'salemm':                            'Salem',
  'saalem':                            'Salem',
  'selem':                             'Salem',
  'saleem':                            'Salem',
  'sailem':                            'Salem',
  'saelm':                             'Salem',

  // Erode
  'eroad':                             'Erode',
  'eroud':                             'Erode',
  'errode':                            'Erode',
  'erode dt':                          'Erode',
  'erood':                             'Erode',
  'erod':                              'Erode',
  'irode':                             'Erode',

  // Tirunelveli
  'nelai':                             'Tirunelveli',
  'tirunelvely':                       'Tirunelveli',
  'thirunelveli':                      'Tirunelveli',
  'tirunelvelii':                      'Tirunelveli',
  'tirunelveli dt':                    'Tirunelveli',
  'tirunalveli':                       'Tirunelveli',
  'tirunalvely':                       'Tirunelveli',
  'tirunalvelli':                      'Tirunelveli',
  'tirunelveli city':                  'Tirunelveli',
  'tirunelveli town':                  'Tirunelveli',
  'tinnevelly':                        'Tirunelveli',
  'tinneveli':                         'Tirunelveli',

  // Vellore
  'vellur':                            'Vellore',
  'velloore':                          'Vellore',
  'vellor':                            'Vellore',
  'velore':                            'Vellore',
  'veloor':                            'Vellore',
  'velor':                             'Vellore',
  'vallore':                           'Vellore',
  'valore':                            'Vellore',

  // Thanjavur
  'tanjavur':                          'Thanjavur',
  'tanjore dt':                        'Thanjavur',
  'thanjore':                          'Thanjavur',
  'thanjor':                           'Thanjavur',
  'thanjavoor':                        'Thanjavur',
  'thanjur':                           'Thanjavur',
  'tanjur':                            'Thanjavur',
  'thanjavurr':                        'Thanjavur',
  'tanjoor':                           'Thanjavur',

  // Kanchipuram
  'kancheepuaram':                     'Kanchipuram',
  'kanchipuaram':                      'Kanchipuram',
  'kanchipuram dt':                    'Kanchipuram',
  'conjeevaram':                       'Kanchipuram',
  'kancheepurm':                       'Kanchipuram',
  'kanchipurm':                        'Kanchipuram',
  'kanchpuram':                        'Kanchipuram',
  'kanchipuran':                       'Kanchipuram',

  // Chengalpattu
  'chengalpattu dt':                   'Chengalpattu',
  'chengalpattu city':                 'Chengalpattu',
  'chengalpatu':                       'Chengalpattu',
  'chengalpet dt':                     'Chengalpattu',
  'chengalpatoo':                      'Chengalpattu',
  'chengalpattu new':                  'Chengalpattu',
  'chengalpttu':                       'Chengalpattu',
  'chnegalpattu':                      'Chengalpattu',

  // Villupuram
  'viluppuram':                        'Villupuram',
  'villupuaram':                       'Villupuram',
  'villupuran':                        'Villupuram',
  'villupurom':                        'Villupuram',
  'villuppuuram':                      'Villupuram',
  'vilipuram':                         'Villupuram',

  // Cuddalore
  'cudaloor':                          'Cuddalore',
  'cudalur':                           'Cuddalore',
  'kuddalur':                          'Cuddalore',
  'cuddlore':                          'Cuddalore',
  'cuddaore':                          'Cuddalore',
  'cuddaalore':                        'Cuddalore',
  'cudalora':                          'Cuddalore',
  'cuddaloor':                         'Cuddalore',

  // Kumbakonam
  'kumbakonam dt':                     'Kumbakonam',
  'kumbakonum city':                   'Kumbakonam',
  'kumbakonam city':                   'Kumbakonam',
  'kumbakonm':                         'Kumbakonam',
  'kumbakoanum':                       'Kumbakonam',
  'kumbakonum town':                   'Kumbakonam',
  'kumbaconm':                         'Kumbakonam',
  'kumbakonum dt':                     'Kumbakonam',
  'kumbakoanam':                       'Kumbakonam',

  // Nagapattinam
  'nagapatnam':                        'Nagapattinam',
  'nagapattinam dt':                   'Nagapattinam',
  'nagapatnam dt':                     'Nagapattinam',
  'nagapattanam':                      'Nagapattinam',
  'nagapattnam':                       'Nagapattinam',
  'nagapatinam dt':                    'Nagapattinam',
  'nagapattinam city':                 'Nagapattinam',
  'nagpatinam':                        'Nagapattinam',

  // Dindigul
  'dindigal':                          'Dindigul',
  'dindikal':                          'Dindigul',
  'dindugul':                          'Dindigul',
  'dindugal dt':                       'Dindigul',
  'dindigul dt':                       'Dindigul',
  'dindugul dt':                       'Dindigul',
  'dindikkal':                         'Dindigul',
  'dindikl':                           'Dindigul',

  // Tiruppur
  'tirupur dt':                        'Tiruppur',
  'tiruppur dt':                       'Tiruppur',
  'tiruppur city':                     'Tiruppur',
  'tirupur city':                      'Tiruppur',
  'thiruppur':                         'Tiruppur',
  'thirupur':                          'Tiruppur',
  'tirupure':                          'Tiruppur',
  'tirupurr':                          'Tiruppur',
  'tiruppurr':                         'Tiruppur',
  'tiruupur':                          'Tiruppur',

  // Hosur
  'hosoor':                            'Hosur',
  'hosurr':                            'Hosur',
  'hosure':                            'Hosur',
  'hosour':                            'Hosur',
  'hossur':                            'Hosur',

  // Krishnagiri
  'krishnagri':                        'Krishnagiri',
  'krishnagiri dt':                    'Krishnagiri',
  'krishnagiry':                       'Krishnagiri',
  'krishnagiri town':                  'Krishnagiri',
  'krishnagari':                       'Krishnagiri',
  'krshnagiri':                        'Krishnagiri',
  'krishanagiri':                      'Krishnagiri',

  // Dharmapuri
  'dharmapurii':                       'Dharmapuri',
  'dharmapury':                        'Dharmapuri',
  'dharamapuri':                       'Dharmapuri',
  'dharmapuri dt':                     'Dharmapuri',
  'dharampur':                         'Dharmapuri',
  'dharmpur':                          'Dharmapuri',
  'darmapuri':                         'Dharmapuri',
  'dharmapure':                        'Dharmapuri',

  // Namakkal
  'namakall':                          'Namakkal',
  'namakkal dt':                       'Namakkal',
  'namakkal town':                     'Namakkal',
  'namakal':                           'Namakkal',
  'namakaal':                          'Namakkal',
  'namakul':                           'Namakkal',

  // Karur
  'karoor':                            'Karur',
  'karrur':                            'Karur',
  'karurr':                            'Karur',
  'karur dt':                          'Karur',
  'karuor':                            'Karur',
  'karuur':                            'Karur',

  // Perambalur
  'perambaloor':                       'Perambalur',
  'perambalur dt':                     'Perambalur',
  'perambalur town':                   'Perambalur',
  'perabalur':                         'Perambalur',
  'perambalir':                        'Perambalur',
  'peramblur':                         'Perambalur',

  // Ariyalur
  'ariyaloor':                         'Ariyalur',
  'ariyalur dt':                       'Ariyalur',
  'ariyalur town':                     'Ariyalur',
  'ariyalure':                         'Ariyalur',
  'arialur':                           'Ariyalur',
  'arialoor':                          'Ariyalur',
  'ariyalurr':                         'Ariyalur',

  // Sivaganga
  'sivagangai':                        'Sivaganga',
  'sivagangai dt':                     'Sivaganga',
  'sivaganga dt':                      'Sivaganga',
  'sivagangaa':                        'Sivaganga',
  'sivagangai town':                   'Sivaganga',
  'shivaganga':                        'Sivaganga',
  'shivagangai':                       'Sivaganga',
  'sivagangay':                        'Sivaganga',

  // Virudhunagar
  'virudhunagr':                       'Virudhunagar',
  'virudhunagar dt':                   'Virudhunagar',
  'virudunagar':                       'Virudhunagar',
  'virudunagr':                        'Virudhunagar',
  'virudhunagaar':                     'Virudhunagar',
  'virudunagar dt':                    'Virudhunagar',
  'virudhunagr town':                  'Virudhunagar',
  'virudhunagur':                      'Virudhunagar',

  // Ramanathapuram
  'ramnathapuram':                     'Ramanathapuram',
  'ramnathpuram':                      'Ramanathapuram',
  'ramnad':                            'Ramanathapuram',
  'ramanathpuram':                     'Ramanathapuram',
  'ramanadhapuram':                    'Ramanathapuram',
  'ramanadapuram':                     'Ramanathapuram',
  'ramanathapuram dt':                 'Ramanathapuram',
  'ramnad dt':                         'Ramanathapuram',

  // Thoothukudi
  'thoothkudi':                        'Thoothukudi',
  'thootukudi':                        'Thoothukudi',
  'tutucrin':                          'Thoothukudi',
  'tuticorin dt':                      'Thoothukudi',
  'thoothukudi dt':                    'Thoothukudi',
  'thoothucudi':                       'Thoothukudi',
  'thoothukudy':                       'Thoothukudi',
  'thothukudi':                        'Thoothukudi',
  'thoothicudi':                       'Thoothukudi',
  'tuti':                              'Thoothukudi',

  // Kanyakumari
  'kanniyakumari':                     'Kanyakumari',
  'kannyakumari':                      'Kanyakumari',
  'kanyakumari dt':                    'Kanyakumari',
  'kanyakumari dist':                  'Kanyakumari',
  'kanyakumary':                       'Kanyakumari',
  'kaniyakumari':                      'Kanyakumari',
  'kanyakuamri':                       'Kanyakumari',
  'kanyakumri':                        'Kanyakumari',
  'cape comorin':                      'Kanyakumari',

  // Nagercoil
  'nagerkoil':                         'Nagercoil',
  'nagarcoil':                         'Nagercoil',
  'nagarkoil':                         'Nagercoil',
  'nagercoil city':                    'Nagercoil',
  'nagercoil town':                    'Nagercoil',
  'nagercoill':                        'Nagercoil',
  'nagerkoill':                        'Nagercoil',
  'nagercoyi':                         'Nagercoil',
  'nagerkoyi':                         'Nagercoil',

  // Tiruvannamalai
  'tiruvannamalai':                    'Tiruvannamalai',
  'thiruvannamalai':                   'Tiruvannamalai',
  'tiruvannamalai dt':                 'Tiruvannamalai',
  'thiruvannamalai dt':                'Tiruvannamalai',
  'tiruvannamalai city':               'Tiruvannamalai',
  'tiruvannamalai town':               'Tiruvannamalai',
  'tiruvannamalai temple':             'Tiruvannamalai',
  'thiruvannamalai temple':            'Tiruvannamalai',
  'tiruvannamalai hill':               'Tiruvannamalai',
  'tvm':                               'Tiruvannamalai',
  'tiruvanamali':                      'Tiruvannamalai',
  'thiruvanamali':                     'Tiruvannamalai',
  'tiruannamalai':                     'Tiruvannamalai',
  'arunachalam':                       'Tiruvannamalai',

  // The Nilgiris
  'the nilgiris':                      'The Nilgiris',
  'nilgiris':                          'The Nilgiris',
  'nilgiri':                           'The Nilgiris',
  'ooty':                              'Ooty',
  'udhagamandalam':                    'Ooty',
  'udagamandalam':                     'Ooty',
  'udhagamandlam':                     'Ooty',
  'ootacamund':                        'Ooty',
  'ootacamundh':                       'Ooty',
  'ooty hills':                        'Ooty',
  'ootty':                             'Ooty',
  'ooty town':                         'Ooty',
  'coonoor':                           'Coonoor',
  'conoor':                            'Coonoor',
  'koonnor':                           'Coonoor',
  'coonor':                            'Coonoor',
  'kotagiri':                          'Kotagiri',
  'kotagiry':                          'Kotagiri',
  'kotakiri':                          'Kotagiri',
  'gudalur':                           'Gudalur',
  'goodalur':                          'Gudalur',
  'gudaloor':                          'Gudalur',

  // Tenkasi
  'tenkasi':                           'Tenkasi',
  'tenkasi dt':                        'Tenkasi',
  'tenkasi town':                      'Tenkasi',
  'thenkasi':                          'Tenkasi',
  'thenkaasi':                         'Tenkasi',
  'tenkasy':                           'Tenkasi',
  'thenkasy':                          'Tenkasi',
  'tenkaze':                           'Tenkasi',

  // Ranipet
  'ranipet':                           'Ranipet',
  'ranipet dt':                        'Ranipet',
  'ranipet town':                      'Ranipet',
  'ranippet':                          'Ranipet',
  'ranipett':                          'Ranipet',
  'ranipet city':                      'Ranipet',

  // Tirupattur
  'tirupattur':                        'Tirupattur',
  'tirupattur dt':                     'Tirupattur',
  'tirupattur town':                   'Tirupattur',
  'thirupattur':                       'Tirupattur',
  'tirupatur':                         'Tirupattur',
  'thirupatur':                        'Tirupattur',
  'tirupatturr':                       'Tirupattur',

  // Kallakurichi
  'kallakurichi':                      'Kallakurichi',
  'kallakurchi':                       'Kallakurichi',
  'kallakuruichi':                     'Kallakurichi',
  'kallakurichi dt':                   'Kallakurichi',
  'kallakuichi':                       'Kallakurichi',
  'kallakurichi town':                 'Kallakurichi',

  // Mayiladuthurai
  'mayiladuthurai':                    'Mayiladuthurai',
  'mayilaaduthurai':                   'Mayiladuthurai',
  'mayiladuthurai dt':                 'Mayiladuthurai',
  'mayiladuthurai city':               'Mayiladuthurai',
  'mayiladudurai':                     'Mayiladuthurai',
  'mayladuthurai':                     'Mayiladuthurai',
  'myladuthurai':                      'Mayiladuthurai',
  'myladuturai':                       'Mayiladuthurai',

  // Pudukkottai
  'pudukkottai':                       'Pudukkottai',
  'pudukkotai':                        'Pudukkottai',
  'pudukottai':                        'Pudukkottai',
  'pudukottai dt':                     'Pudukkottai',
  'pudukkottai dt':                    'Pudukkottai',
  'pudukkottai town':                  'Pudukkottai',
  'pudukotai':                         'Pudukkottai',
  'pudukkotaai':                       'Pudukkottai',
  'podukottai':                        'Pudukkottai',

  // Chennai Localities
  't nagar':                           'T. Nagar',
  't.nagar':                           'T. Nagar',
  'thyagaraja nagar':                  'T. Nagar',
  'thyagaraya nagar':                  'T. Nagar',
  't.nagar chennai':                   'T. Nagar',
  'tnagarchennai':                     'T. Nagar',
  'mylapur':                           'Mylapore',
  'mylapore chennai':                  'Mylapore',
  'milapore':                          'Mylapore',
  'mailpore':                          'Mylapore',
  'mylapoor':                          'Mylapore',
  'myllapore':                         'Mylapore',
  'mylapure':                          'Mylapore',
  'velachery chennai':                 'Velachery',
  'velaachery':                        'Velachery',
  'velacherychennai':                  'Velachery',
  'velachari':                         'Velachery',
  'velachary':                         'Velachery',
  'adyar chennai':                     'Adyar',
  'adiar':                             'Adyar',
  'aadyar':                            'Adyar',
  'adiyar':                            'Adyar',
  'anna nagar':                        'Anna Nagar',
  'annanagarchennai':                  'Anna Nagar',
  'anna nagar chennai':                'Anna Nagar',
  'annanagar east':                    'Anna Nagar',
  'annanagar west':                    'Anna Nagar',
  'annanagr east':                     'Anna Nagar',
  'tambarom':                          'Tambaram',
  'tambaram chennai':                  'Tambaram',
  'thamabaram':                        'Tambaram',
  'tamabaram':                         'Tambaram',
  'tambram':                           'Tambaram',
  'tamabram':                          'Tambaram',
  'thambaram':                         'Tambaram',
  'chromepet chennai':                 'Chromepet',
  'chromapet':                         'Chromepet',
  'chrompet chennai':                  'Chromepet',
  'cromepet':                          'Chromepet',
  'cromapete':                         'Chromepet',
  'cromepete':                         'Chromepet',
  'peramabur':                         'Perambur',
  'perambur chennai':                  'Perambur',
  'perambar':                          'Perambur',
  'peramboor':                         'Perambur',
  'ambattoor':                         'Ambattur',
  'ambattur chennai':                  'Ambattur',
  'ambatur':                           'Ambattur',
  'ambatoor':                          'Ambattur',
  'ambatturr':                         'Ambattur',
  'avadi chennai':                     'Avadi',
  'avady':                             'Avadi',
  'avaadi':                            'Avadi',
  'porur chennai':                     'Porur',
  'poroor':                            'Porur',
  'porrur':                            'Porur',
  'poorur':                            'Porur',
  'guindy chennai':                    'Guindy',
  'guindi':                            'Guindy',
  'gunidy':                            'Guindy',
  'guindya':                           'Guindy',
  'kodambakam':                        'Kodambakkam',
  'kodambakkam chennai':               'Kodambakkam',
  'kodamabakkam':                      'Kodambakkam',
  'kodambkam':                         'Kodambakkam',
  'kodambackam':                       'Kodambakkam',
  'nungambakam':                       'Nungambakkam',
  'nungambakkam chennai':              'Nungambakkam',
  'nungabakkam':                       'Nungambakkam',
  'nungambakkm':                       'Nungambakkam',
  'nungambakm':                        'Nungambakkam',
  'egmore chennai':                    'Egmore',
  'egmoore':                           'Egmore',
  'egmoor':                            'Egmore',
  'egmoire':                           'Egmore',
  'royapeta':                          'Royapettah',
  'royapettah chennai':                'Royapettah',
  'royapetah':                         'Royapettah',
  'royappettah':                       'Royapettah',
  'royapettai':                        'Royapettah',
  'triplicane chennai':                'Triplicane',
  'triplicane area':                   'Triplicane',
  'thiru allikkeni':                   'Triplicane',
  'tiruvallikkeni':                    'Triplicane',
  'tiriplicane':                       'Triplicane',
  'tondiarpet chennai':                'Tondiarpet',
  'tondiyarpet':                       'Tondiarpet',
  'tondiarpet area':                   'Tondiarpet',
  'toniyarpet':                        'Tondiarpet',
  'washermenpet':                      'Washermanpet',
  'washermanpet chennai':              'Washermanpet',
  'washermanpet area':                 'Washermanpet',
  'vashermanpet':                      'Washermanpet',
  'wasermanpet':                       'Washermanpet',
  'thiruvotiyur':                      'Thiruvottiyur',
  'thiruvottiyur chennai':             'Thiruvottiyur',
  'thiruvotriyur':                     'Thiruvottiyur',
  'thiruvottiyur area':                'Thiruvottiyur',
  'thiruvottiyur town':                'Thiruvottiyur',
  'thiruvottiyur locality':            'Thiruvottiyur',
  'thiruvoottiyur':                    'Thiruvottiyur',
  'sholinganalur':                     'Sholinganallur',
  'sholinganallur chennai':            'Sholinganallur',
  'sholinganallur it':                 'Sholinganallur',
  'sholingnallur':                     'Sholinganallur',
  'sholinganalur it':                  'Sholinganallur',
  'shollinganallur':                   'Sholinganallur',
  'sholingnallurr':                    'Sholinganallur',
  'perungudi chennai':                 'Perungudi',
  'perungudi it park':                 'Perungudi',
  'perungudii':                        'Perungudi',
  'perungudy':                         'Perungudi',
  'thoraipakam':                       'Thoraipakkam',
  'thoraipakkam chennai':              'Thoraipakkam',
  'thoraipakkam it':                   'Thoraipakkam',
  'thoraipakam it':                    'Thoraipakkam',
  'thoraipakm':                        'Thoraipakkam',
  'thoaraipakkam':                     'Thoraipakkam',
  'pallikarani':                       'Pallikaranai',
  'pallikaranai chennai':              'Pallikaranai',
  'pallikarani area':                  'Pallikaranai',
  'pallikarni':                        'Pallikaranai',
  'pallikaranai area':                 'Pallikaranai',
  'medavakam':                         'Medavakkam',
  'medavakkam chennai':                'Medavakkam',
  'medavakam area':                    'Medavakkam',
  'medavakm':                          'Medavakkam',
  'medavakkm':                         'Medavakkam',
  'madipakam':                         'Madipakkam',
  'madipakkam chennai':                'Madipakkam',
  'madipakm':                          'Madipakkam',
  'madipakkm':                         'Madipakkam',
  'nanganallur chennai':               'Nanganallur',
  'nangnalur':                         'Nanganallur',
  'nangnallur':                        'Nanganallur',
  'nanganallur area':                  'Nanganallur',
  'nanganalur':                        'Nanganallur',
  'alandur chennai':                   'Alandur',
  'alandoor':                          'Alandur',
  'aalandur':                          'Alandur',
  'alandur area':                      'Alandur',
  'saidapet chennai':                  'Saidapet',
  'saidapett':                         'Saidapet',
  'saiadapet':                         'Saidapet',
  'saidapet area':                     'Saidapet',
  'saidapet locality':                 'Saidapet',
  'kottupuram':                        'Kotturpuram',
  'kotturpuram chennai':               'Kotturpuram',
  'kotturpuarm':                       'Kotturpuram',
  'kotturpuramm':                      'Kotturpuram',
  'besant nagar chennai':              'Besant Nagar',
  'besant nagr':                       'Besant Nagar',
  'besant nagarchennai':               'Besant Nagar',
  'besantnagar beach':                 'Besant Nagar',
  'besanthnager':                      'Besant Nagar',
  'thiruvanmiyur':                     'Thiruvanmiyur',
  'thiruvanmiyur chennai':             'Thiruvanmiyur',
  'thiruvanmiyur beach':               'Thiruvanmiyur',
  'thiruvanmiyurr':                    'Thiruvanmiyur',
  'thiruvanmiyur area':                'Thiruvanmiyur',
  'tiruvanmiyur':                      'Thiruvanmiyur',
  'palavakkam':                        'Palavakkam',
  'palavakam':                         'Palavakkam',
  'palavakkam beach':                  'Palavakkam',
  'palavakm':                          'Palavakkam',
  'injambakkam':                       'Injambakkam',
  'injambakam':                        'Injambakkam',
  'injambakkam chennai':               'Injambakkam',
  'injambakm':                         'Injambakkam',
  'kottivakkam':                       'Kottivakkam',
  'kottivakam':                        'Kottivakkam',
  'kottivakm':                         'Kottivakkam',
  'mugalivakkam':                      'Mugalivakkam',
  'mugalivakam':                       'Mugalivakkam',
  'mugalivakm':                        'Mugalivakkam',
  'poonamallee':                       'Poonamallee',
  'poonamallee chennai':               'Poonamallee',
  'poonamalee':                        'Poonamallee',
  'punamallee':                        'Poonamallee',
  'punamalee':                         'Poonamallee',
  'poonamallee highway':               'Poonamallee',
  'poonamalee highway':                'Poonamallee',
  'poonamallee high road':             'Poonamallee',
  'manali':                            'Manali',
  'manali chennai':                    'Manali',
  'manalii':                           'Manali',
  'manaly':                            'Manali',
  'tiruvallur':                        'Tiruvallur',
  'thiruvallur':                       'Tiruvallur',
  'thiruvallur dt':                    'Tiruvallur',
  'thiruvallur town':                  'Tiruvallur',
  'tiruvallur dt':                     'Tiruvallur',
  'tiruvalur':                         'Tiruvallur',
  'thiruvalur':                        'Tiruvallur',
  'tiruvalloor':                       'Tiruvallur',
  'thiruvalloor':                      'Tiruvallur',

  // Madurai Area
  'anna nagar madurai':                'Anna Nagar, Madurai',
  'annanagar madurai':                 'Anna Nagar, Madurai',
  'k k nagar madurai':                 'KK Nagar, Madurai',
  'kk nagar madurai':                  'KK Nagar, Madurai',
  'kknagar madurai':                   'KK Nagar, Madurai',
  'kkn madurai':                       'KK Nagar, Madurai',
  'ss colony madurai':                 'SS Colony, Madurai',
  'sscolony madurai':                  'SS Colony, Madurai',
  'simmakkal':                         'Simmakkal',
  'simmakkal madurai':                 'Simmakkal',
  'simakkal':                          'Simmakkal',
  'simakkal madurai':                  'Simmakkal',
  'simmakkal area':                    'Simmakkal',
  'iyer bungalow':                     'Iyer Bungalow',
  'iyer bungalow madurai':             'Iyer Bungalow',
  'iyerbungalow':                      'Iyer Bungalow',
  'iyer bunglow':                      'Iyer Bungalow',
  'palanganatham':                     'Palanganatham',
  'palanganatham madurai':             'Palanganatham',
  'palganatham':                       'Palanganatham',
  'palanganatam':                      'Palanganatham',
  'anuppanadi':                        'Anuppanadi',
  'anuppanadi madurai':                'Anuppanadi',
  'anupanadi':                         'Anuppanadi',
  'villapuram madurai':                'Villapuram, Madurai',
  'villapuram':                        'Villapuram, Madurai',
  'goripalayam':                       'Goripalayam',
  'goripalayam madurai':               'Goripalayam',
  'gorippaalyam':                      'Goripalayam',
  'goripaalyam':                       'Goripalayam',
  'bye pass road madurai':             'Bypass Road, Madurai',
  'bypass madurai':                    'Bypass Road, Madurai',
  'bypass road madurai':               'Bypass Road, Madurai',
  'madurai bypass':                    'Bypass Road, Madurai',
  'tallakulam':                        'Tallakulam',
  'tallakulam madurai':                'Tallakulam',
  'thallakulam':                       'Tallakulam',
  'thalakkulam':                       'Tallakulam',
  'alagar kovil road':                 'Alagar Kovil Road',
  'alagarkoil road':                   'Alagar Kovil Road',
  'alagar koil road':                  'Alagar Kovil Road',
  'alagar kovil rd':                   'Alagar Kovil Road',
  'thirunagar':                        'Thirunagar',
  'thirunagar madurai':                'Thirunagar',
  'thiru nagar madurai':               'Thirunagar',
  'teppakulam':                        'Teppakulam',
  'teppakulam madurai':                'Teppakulam',
  'teppakulam area':                   'Teppakulam',
  'teppakulam locality':               'Teppakulam',

  // Coimbatore Localities
  'rs puram':                          'RS Puram',
  'r s puram':                         'RS Puram',
  'rspuram':                           'RS Puram',
  'r.s.puram':                         'RS Puram',
  'rs puram coimbatore':               'RS Puram',
  'gandhipuram':                       'Gandhipuram',
  'gandhipuram coimbatore':            'Gandhipuram',
  'gandipuram':                        'Gandhipuram',
  'gandipuarm':                        'Gandhipuram',
  'ramanathapuram coimbatore':         'Ramanathapuram, Coimbatore',
  'ramanathapuram cbe':                'Ramanathapuram, Coimbatore',
  'sidhapudur':                        'Sidhapudur',
  'sidhapudur coimbatore':             'Sidhapudur',
  'sidapudur':                         'Sidhapudur',
  'peelamedu':                         'Peelamedu',
  'peelamedu coimbatore':              'Peelamedu',
  'peelamedu airport':                 'Peelamedu',
  'peelaamedu':                        'Peelamedu',
  'saravanampatti':                    'Saravanampatti',
  'saravanampati':                     'Saravanampatti',
  'saravanampatti coimbatore':         'Saravanampatti',
  'saravanampattii':                   'Saravanampatti',
  'hopes college':                     'Hopes College Area, Coimbatore',
  'hope college cbe':                  'Hopes College Area, Coimbatore',
  'ganapathy coimbatore':              'Ganapathy',
  'ganapathy':                         'Ganapathy',
  'ganapathy cbe':                     'Ganapathy',
  'singanallur':                       'Singanallur',
  'singanallur coimbatore':            'Singanallur',
  'singnallur':                        'Singanallur',
  'sowripalayam':                      'Sowripalayam',
  'sowripalayam cbe':                  'Sowripalayam',
  'sowrippalaym':                      'Sowripalayam',
  'vadavalli':                         'Vadavalli',
  'vadavalli coimbatore':              'Vadavalli',
  'vadavali':                          'Vadavalli',
  'kuniyamuthur':                      'Kuniyamuthur',
  'kuniyamuttur':                      'Kuniyamuthur',
  'kuniyamuthur coimbatore':           'Kuniyamuthur',
  'thudiyalur':                        'Thudiyalur',
  'thudiyalur coimbatore':             'Thudiyalur',
  'tudiyalur':                         'Thudiyalur',
  'ondipudur':                         'Ondipudur',
  'ondipudur coimbatore':              'Ondipudur',
  'ondipudur area':                    'Ondipudur',
  'podanur':                           'Podanur',
  'podanur coimbatore':                'Podanur',
  'pollachi':                          'Pollachi',
  'pollachi coimbatore':               'Pollachi',
  'polachi':                           'Pollachi',
  'palladam':                          'Palladam',
  'palladam coimbatore':               'Palladam',
  'annur':                             'Annur',
  'annur coimbatore':                  'Annur',
  'mettupalayam':                      'Mettupalayam',
  'mettupalayam coimbatore':           'Mettupalayam',
  'mettupalayam town':                 'Mettupalayam',
  'mettupalaiyam':                     'Mettupalayam',

  // Trichy Localities
  'srirangam':                         'Srirangam',
  'srirangam trichy':                  'Srirangam',
  'sri rangam':                        'Srirangam',
  'srirangam temple':                  'Srirangam',
  'thiruvarangam':                     'Srirangam',
  'golden rock':                       'Golden Rock',
  'golden rock trichy':                'Golden Rock',
  'goldenrock':                        'Golden Rock',
  'woraiyur':                          'Woraiyur',
  'woraiyur trichy':                   'Woraiyur',
  'woraiyur area':                     'Woraiyur',
  'puthur':                            'Puthur',
  'puthur trichy':                     'Puthur',
  'puthur area':                       'Puthur',
  'kattur':                            'Kattur',
  'kattur trichy':                     'Kattur',
  'ariyamangalam':                     'Ariyamangalam',
  'ariyamangalam trichy':              'Ariyamangalam',
  'k k nagar trichy':                  'KK Nagar, Trichy',
  'kk nagar trichy':                   'KK Nagar, Trichy',
  'manachanallur':                     'Manachanallur',
  'manapparai':                        'Manapparai',
  'manapparai trichy':                 'Manapparai',
  'musiri':                            'Musiri',
  'musiri trichy':                     'Musiri',
  'lalgudi':                           'Lalgudi',
  'lalgudi trichy':                    'Lalgudi',

  // Salem Localities
  'fairlands':                         'Fairlands',
  'fairlands salem':                   'Fairlands',
  'fair lands salem':                  'Fairlands',
  'swarnapuri':                        'Swarnapuri',
  'swarnapuri salem':                  'Swarnapuri',
  'shevapet':                          'Shevapet',
  'shevapet salem':                    'Shevapet',
  'four roads salem':                  'Four Roads, Salem',
  '4 roads salem':                     'Four Roads, Salem',
  'attur':                             'Attur',
  'attur salem':                       'Attur',
  'omalur':                            'Omalur',
  'omalur salem':                      'Omalur',
  'mettur':                            'Mettur',
  'mettur salem':                      'Mettur',
  'mettur dam':                        'Mettur Dam',
  'mettur dam area':                   'Mettur Dam',
  'edappadi':                          'Edappadi',
  'edappadi salem':                    'Edappadi',
  'sankari':                           'Sankari',
  'sankari salem':                     'Sankari',

  // Vellore / Ranipet Localities
  'katpadi':                           'Katpadi',
  'katpadi vellore':                   'Katpadi',
  'sathuvachari':                      'Sathuvachari',
  'sathuvachari vellore':              'Sathuvachari',
  'gandhi nagar vellore':              'Gandhi Nagar, Vellore',
  'gandhinagar vellore':               'Gandhi Nagar, Vellore',
  'walajah':                           'Walajah',
  'walajah ranipet':                   'Walajah',
  'arcot':                             'Arcot',
  'arcot ranipet':                     'Arcot',
  'ambur':                             'Ambur',
  'ambur vellore':                     'Ambur',
  'vaniyambadi':                       'Vaniyambadi',
  'vaniyambadi tirupattur':            'Vaniyambadi',
  'jolarpet':                          'Jolarpet',
  'jolarpet tirupattur':               'Jolarpet',

  // Tirunelveli / Tenkasi Localities
  'palayamkottai':                     'Palayamkottai',
  'palayamkottai tirunelveli':         'Palayamkottai',
  'palayamkotai':                      'Palayamkottai',
  'palayankottai':                     'Palayamkottai',
  'palyamkottai':                      'Palayamkottai',
  'pettai tirunelveli':                'Pettai',
  'pettai':                            'Pettai',
  'melapalayam':                       'Melapalayam',
  'melapalayam tirunelveli':           'Melapalayam',
  'mela palayam':                      'Melapalayam',
  'nanguneri':                         'Nanguneri',
  'nanguneri tirunelveli':             'Nanguneri',
  'sankarankovil':                     'Sankarankovil',
  'sankarankovil tenkasi':             'Sankarankovil',
  'shenkottai':                        'Shenkottai',
  'shenkottai tenkasi':                'Shenkottai',
  'vikramasingapuram':                 'Vikramasingapuram',
  'vickramasingapuram':                'Vikramasingapuram',

  // Kanyakumari Localities
  'marthandam':                        'Marthandam',
  'marthandam kanyakumari':            'Marthandam',
  'marthandom':                        'Marthandam',
  'colachel':                          'Colachel',
  'colachel kanyakumari':              'Colachel',
  'kulasekarapattinam':                'Kulasekarapattinam',
  'thuckalay':                         'Thuckalay',
  'thuckalay kanyakumari':             'Thuckalay',
  'kuzhithurai':                       'Kuzhithurai',
  'kuzhithurai kanyakumari':           'Kuzhithurai',
  'eraniel':                           'Eraniel',
  'padmanabhapuram':                   'Padmanabhapuram',

  // Erode / Tiruppur Localities
  'bhavani':                           'Bhavani',
  'bhavani erode':                     'Bhavani',
  'gobichettipalayam':                 'Gobichettipalayam',
  'gobi':                              'Gobichettipalayam',
  'gobi erode':                        'Gobichettipalayam',
  'gobi chettipalayam':                'Gobichettipalayam',
  'gobichetipalaym':                   'Gobichettipalayam',
  'sathyamangalam':                    'Sathyamangalam',
  'sathyamangalam erode':              'Sathyamangalam',
  'satyamangalam':                     'Sathyamangalam',
  'anthiyur':                          'Anthiyur',
  'anthiyur erode':                    'Anthiyur',
  'perundurai':                        'Perundurai',
  'perundurai erode':                  'Perundurai',
  'kangayam':                          'Kangayam',
  'kangayam tiruppur':                 'Kangayam',
  'dharapuram':                        'Dharapuram',
  'dharapuram tiruppur':               'Dharapuram',
  'udumalpet':                         'Udumalpet',
  'udumalpet tiruppur':                'Udumalpet',
  'udumalapet':                        'Udumalpet',
  'avinashi':                          'Avinashi',
  'avinashi tiruppur':                 'Avinashi',

  // Puducherry Localities
  'white town pondicherry':            'White Town, Puducherry',
  'white town pondy':                  'White Town, Puducherry',
  'white town':                        'White Town, Puducherry',
  'villianur':                         'Villianur',
  'villianur pondicherry':             'Villianur',
  'villiyanur':                        'Villianur',
  'villiyanur pondy':                  'Villianur',
  'lawspet':                           'Lawspet',
  'lawspet pondicherry':               'Lawspet',
  'lawspet pondy':                     'Lawspet',
  'lawpet':                            'Lawspet',
  'mudaliarpet':                       'Mudaliarpet',
  'mudaliarpet pondicherry':           'Mudaliarpet',
  'mudaliarpet pondy':                 'Mudaliarpet',
  'mudliarpet':                        'Mudaliarpet',
  'reddiyarpalayam':                   'Reddiyarpalayam',
  'reddiyarpalayam pondicherry':       'Reddiyarpalayam',
  'reddiarpalayam':                    'Reddiyarpalayam',
  'reddiarpalayam pondy':              'Reddiyarpalayam',
  'ariyankuppam':                      'Ariyankuppam',
  'ariyankuppam pondicherry':          'Ariyankuppam',
  'ariankoopam':                       'Ariyankuppam',
  'auroville':                         'Auroville',
  'auroville pondicherry':             'Auroville',
  'auro ville':                        'Auroville',
  'aurora ville':                      'Auroville',
  'tindivanam':                        'Tindivanam',
  'tindivanam villupuram':             'Tindivanam',
  'thindivanam':                       'Tindivanam',
  'karaikal':                          'Karaikal',
  'karaikal pondicherry':              'Karaikal',
  'karaikkal':                         'Karaikal',
  'karikal':                           'Karaikal',
  'mahe':                              'Mahe',
  'mahe pondicherry':                  'Mahe',
  'yanam':                             'Yanam',
  'yanam pondicherry':                 'Yanam',

  // Thanjavur / Kumbakonam / Nagapattinam
  'papanasam':                         'Papanasam',
  'papanasam thanjavur':               'Papanasam',
  'pappanasam':                        'Papanasam',
  'pattukkottai':                      'Pattukkottai',
  'pattukkottai thanjavur':            'Pattukkottai',
  'patukottai':                        'Pattukkottai',
  'pattukottai':                       'Pattukkottai',
  'peravurani':                        'Peravurani',
  'peravurani thanjavur':              'Peravurani',
  'orathanadu':                        'Orathanadu',
  'orathanadu thanjavur':              'Orathanadu',
  'budalur':                           'Budalur',
  'budalur thanjavur':                 'Budalur',
  'thiruvidaimarudur':                 'Thiruvidaimarudur',
  'thiruvidaimarudur kumbakonam':      'Thiruvidaimarudur',
  'thiruvidaimaruthur':                'Thiruvidaimarudur',
  'sirkazhi':                          'Sirkazhi',
  'sirkazhi nagapattinam':             'Sirkazhi',
  'siragali':                          'Sirkazhi',
  'sirkali':                           'Sirkazhi',
  'vedaranyam':                        'Vedaranyam',
  'vedaranyam nagapattinam':           'Vedaranyam',
  'kollidam':                          'Kollidam',
  'kollidam nagapattinam':             'Kollidam',

  // Dharmapuri / Krishnagiri / Hosur
  'pochampalli':                       'Pochampalli',
  'pochampalli krishnagiri':           'Pochampalli',
  'palacode':                          'Palacode',
  'palacode dharmapuri':               'Palacode',
  'pappireddipatti':                   'Pappireddipatti',
  'pappireddipatti dharmapuri':        'Pappireddipatti',
  'bargur':                            'Bargur',
  'bargur krishnagiri':                'Bargur',
  'veppanahalli':                      'Veppanahalli',
  'veppanahalli krishnagiri':          'Veppanahalli',

  // Dindigul / Namakkal / Karur
  'oddanchatram':                      'Oddanchatram',
  'oddanchatram dindigul':             'Oddanchatram',
  'oddanchatrom':                      'Oddanchatram',
  'natham':                            'Natham',
  'natham dindigul':                   'Natham',
  'vedasandur':                        'Vedasandur',
  'vedasandur dindigul':               'Vedasandur',
  'palani':                            'Palani',
  'palani dindigul':                   'Palani',
  'palanni':                           'Palani',
  'rasipuram':                         'Rasipuram',
  'rasipuram namakkal':                'Rasipuram',
  'tiruchengode':                      'Tiruchengode',
  'tiruchengode namakkal':             'Tiruchengode',
  'tiruchengode town':                 'Tiruchengode',
  'kulithalai':                        'Kulithalai',
  'kulithalai karur':                  'Kulithalai',

  // Sivaganga / Virudhunagar / Ramanathapuram
  'karaikudi':                         'Karaikudi',
  'karaikudi sivaganga':               'Karaikudi',
  'karaikkudi':                        'Karaikudi',
  'devakottai':                        'Devakottai',
  'devakottai sivaganga':              'Devakottai',
  'manamadurai':                       'Manamadurai',
  'manamadurai sivaganga':             'Manamadurai',
  'sivakasi':                          'Sivakasi',
  'sivakasi virudhunagar':             'Sivakasi',
  'sivakasy':                          'Sivakasi',
  'rajapalayam':                       'Rajapalayam',
  'rajapalayam virudhunagar':          'Rajapalayam',
  'aruppukkottai':                     'Aruppukkottai',
  'aruppukkottai virudhunagar':        'Aruppukkottai',
  'arupukkottai':                      'Aruppukkottai',
  'rameswaram':                        'Rameswaram',
  'rameswaram ramanathapuram':         'Rameswaram',
  'rameshwaram':                       'Rameswaram',
  'ramesvaram':                        'Rameswaram',
  'pamban':                            'Pamban',
  'paramakudi':                        'Paramakudi',
  'paramakudi ramanathapuram':         'Paramakudi',
  'mudukulathur':                      'Mudukulathur',
  'mudukulathur ramanathapuram':       'Mudukulathur',

  // Chengalpattu / Kanchipuram
  'mahabalipuram':                     'Mahabalipuram',
  'mamallapuram':                      'Mahabalipuram',
  'mahabalipuram chengalpattu':        'Mahabalipuram',
  'mamallpuram':                       'Mahabalipuram',
  'mahabalipuram beach':               'Mahabalipuram',
  'uthiramerur':                       'Uthiramerur',
  'uthiramerur kanchipuram':           'Uthiramerur',
  'maduranthakam':                     'Maduranthakam',
  'maduranthakam chengalpattu':        'Maduranthakam',
  'cheyyur':                           'Cheyyur',
  'cheyyur chengalpattu':              'Cheyyur',
  'singaperumalkoil':                  'Singaperumalkoil',
  'singaperumalkoil kanchipuram':      'Singaperumalkoil',
  'uttiramerur':                       'Uthiramerur',

  // Tiruvannamalai / Villupuram
  'gingee':                            'Gingee',
  'gingee villupuram':                 'Gingee',
  'senji':                             'Gingee',
  'senji villupuram':                  'Gingee',
  'ulundurpet':                        'Ulundurpet',
  'ulundurpet villupuram':             'Ulundurpet',
  'sankarapuram':                      'Sankarapuram',
  'sankarapuram villupuram':           'Sankarapuram',
  'polur':                             'Polur',
  'polur tiruvannamalai':              'Polur',
  'vandavasi':                         'Vandavasi',
  'vandavasi tiruvannamalai':          'Vandavasi',
  'cheyyar':                           'Cheyyar',
  'cheyyar tiruvannamalai':            'Cheyyar',

  // Cuddalore / Mayiladuthurai
  'chidambaram':                       'Chidambaram',
  'chidambaram cuddalore':             'Chidambaram',
  'chidambaram temple':                'Chidambaram',
  'chidabaram':                        'Chidambaram',
  'cidambaram':                        'Chidambaram',
  'kattumannarkoil':                   'Kattumannarkoil',
  'kattumannarkoil cuddalore':         'Kattumannarkoil',
  'panruti':                           'Panruti',
  'panruti cuddalore':                 'Panruti',
  'virudhachalam':                     'Virudhachalam',
  'virudhachalam cuddalore':           'Virudhachalam',
  'virudachalam':                      'Virudhachalam',
  'tharangambadi':                     'Tharangambadi',
  'tharangambadi nagapattinam':        'Tharangambadi',
  'tranquebar':                        'Tharangambadi',
  'tarangambadi':                      'Tharangambadi',

  // Thoothukudi Localities
  'kovilpatti':                        'Kovilpatti',
  'kovilpatti thoothukudi':            'Kovilpatti',
  'kovilpatty':                        'Kovilpatti',
  'vilathikulam':                      'Vilathikulam',
  'vilathikulam thoothukudi':          'Vilathikulam',
  'ottapidaram':                       'Ottapidaram',
  'ottapidaram thoothukudi':           'Ottapidaram',
  'kayalpattinam':                     'Kayalpattinam',
  'kayalpattinam thoothukudi':         'Kayalpattinam',
  'tiruchendur':                       'Tiruchendur',
  'tiruchendur thoothukudi':           'Tiruchendur',
  'thiruchiendur':                     'Tiruchendur',
  'srivaikuntam':                      'Srivaikuntam',
  'srivaikuntam thoothukudi':          'Srivaikuntam',
  'sri vaikuntam':                     'Srivaikuntam',

  // Pudukkottai / Mayiladuthurai / Ariyalur
  'aranthangi':                        'Aranthangi',
  'aranthangi pudukkottai':            'Aranthangi',
  'alangudi':                          'Alangudi',
  'alangudi pudukkottai':              'Alangudi',
  'thirumayam':                        'Thirumayam',
  'thirumayam pudukkottai':            'Thirumayam',
  'keeranur':                          'Keeranur',
  'keeranur pudukkottai':              'Keeranur',
  'sendurai':                          'Sendurai',
  'sendurai ariyalur':                 'Sendurai',
  'udayarpalayam':                     'Udayarpalayam',
  'udayarpalayam ariyalur':            'Udayarpalayam',
  'sembanarkoil':                      'Sembanarkoil',
  'sembanarkoil mayiladuthurai':       'Sembanarkoil',

  // Common Alternate Spellings
  'voc port':                          'Thoothukudi',
  'voc nagar':                         'Thoothukudi',
  'rock fort':                         'Tiruchirappalli',
  'rock fort trichy':                  'Tiruchirappalli',
  'meenakshi amman temple area':       'Madurai',
  'meenakshi temple area':             'Madurai',
  'ooty hill station':                 'Ooty',
  'nilgiri hills':                     'The Nilgiris',
  'nilgiri hills area':                'The Nilgiris',
  'marina beach area':                 'Chennai',
  'marina chennai':                    'Chennai',
  'cmbt':                              'Chennai',
  'koyambedu':                         'Koyambedu',
  'koyambedu chennai':                 'Koyambedu',
  'koyamabedu':                        'Koyambedu',
  'cmbt bus stand':                    'Koyambedu',
  'koyambedu bus stand':               'Koyambedu',
  'cooptex':                           'Chennai',
  'parry\'s corner':                   'Parrys, Chennai',
  'parrys corner':                     'Parrys, Chennai',
  'parrys':                            'Parrys, Chennai',
  'parris':                            'Parrys, Chennai',
  'broadway chennai':                  'Broadway, Chennai',
  'broadway':                          'Broadway, Chennai',
  'central station chennai':           'Chennai Central',
  'chennai central':                   'Chennai Central',
  'chennai central station':           'Chennai Central',

}