import { ALIAS_MAP } from './aliases'

export interface SeedLocality {
  name: string
  name_normalized: string
  name_phonetic: string
  district: string
  state: string
  locality_type: string
  geonames_id?: number
}

function norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, '')
}

function phonetic(s: string): string {
  return s
    .replace(/ph/g, 'f')
    .replace(/ck/g, 'k')
    .replace(/([aeiou])\1+/g, '$1')
    .replace(/([^aeiou])\1+/g, '$1')
    .replace(/yan/g, 'an')
    .replace(/iya/g, 'ia')
    .replace(/ea/g, 'e')
    .replace(/ou/g, 'u')
    .replace(/[aeiou]+$/, '')
}

function loc(
  name: string,
  district: string,
  state: string,
  locality_type = 'locality',
  geonames_id?: number
): SeedLocality {
  const n = norm(name)
  return { name, name_normalized: n, name_phonetic: phonetic(n), district, state, locality_type, geonames_id }
}

// ── Priority 1: All 65 existing AREAS from lib/areas.ts ──────────────────────
const PONDICHERRY_LOCALITIES: SeedLocality[] = [
  loc('White Town',                 'Puducherry', 'Puducherry', 'locality'),
  loc('Heritage Town',              'Puducherry', 'Puducherry', 'locality'),
  loc('Muthialpet',                 'Puducherry', 'Puducherry', 'locality'),
  loc('Lawspet',                    'Puducherry', 'Puducherry', 'locality'),
  loc('Reddiarpalayam',             'Puducherry', 'Puducherry', 'locality'),
  loc('Mudaliarpet',                'Puducherry', 'Puducherry', 'locality'),
  loc('Rainbow Nagar',              'Puducherry', 'Puducherry', 'locality'),
  loc('Anna Nagar',                 'Puducherry', 'Puducherry', 'locality'),
  loc('Thattanchavady',             'Puducherry', 'Puducherry', 'locality'),
  loc('Venkata Nagar',              'Puducherry', 'Puducherry', 'locality'),
  loc('Saram',                      'Puducherry', 'Puducherry', 'locality'),
  loc('Boomianpet',                 'Puducherry', 'Puducherry', 'locality'),
  loc('Karuvadikuppam',             'Puducherry', 'Puducherry', 'locality'),
  loc('Kuruchikuppam',              'Puducherry', 'Puducherry', 'locality'),
  loc('Vaithikuppam',               'Puducherry', 'Puducherry', 'locality'),
  loc('Dubrayapet',                 'Puducherry', 'Puducherry', 'locality'),
  loc('Orleanpet',                  'Puducherry', 'Puducherry', 'locality'),
  loc('Nellithope',                 'Puducherry', 'Puducherry', 'locality'),
  loc('Gorimedu',                   'Puducherry', 'Puducherry', 'locality'),
  loc('Pakkamudayanpet',            'Puducherry', 'Puducherry', 'locality'),
  loc('Kuyavarpalayam',             'Puducherry', 'Puducherry', 'locality'),
  loc('Periya Mudaliyar Chavadi',   'Puducherry', 'Puducherry', 'locality'),
  loc('Mission Street',             'Puducherry', 'Puducherry', 'locality'),
  loc('Kottakuppam',                'Puducherry', 'Puducherry', 'locality'),
  loc('Ariyankuppam',               'Puducherry', 'Puducherry', 'locality'),
  loc('Veerampattinam',             'Puducherry', 'Puducherry', 'locality'),
  loc('Nonankuppam',                'Puducherry', 'Puducherry', 'locality'),
  loc('Manavely',                   'Puducherry', 'Puducherry', 'locality'),
  loc('Murungapakkam',              'Puducherry', 'Puducherry', 'locality'),
  loc('Abishegapakkam',             'Puducherry', 'Puducherry', 'locality'),
  loc('Kirumampakkam',              'Puducherry', 'Puducherry', 'locality'),
  loc('Pooranankuppam',             'Puducherry', 'Puducherry', 'locality'),
  loc('Pillaiyarkuppam',            'Puducherry', 'Puducherry', 'locality'),
  loc('Bahour',                     'Puducherry', 'Puducherry', 'locality'),
  loc('Kuruvinatham',               'Puducherry', 'Puducherry', 'locality'),
  loc('Karikalampakkam',            'Puducherry', 'Puducherry', 'locality'),
  loc('Nettapakkam',                'Puducherry', 'Puducherry', 'locality'),
  loc('Madukarai',                  'Puducherry', 'Puducherry', 'locality'),
  loc('Embalam',                    'Puducherry', 'Puducherry', 'locality'),
  loc('Korkadu',                    'Puducherry', 'Puducherry', 'locality'),
  loc('Villianur',                  'Puducherry', 'Puducherry', 'locality'),
  loc('Odiampet',                   'Puducherry', 'Puducherry', 'locality'),
  loc('Sedarapet',                  'Puducherry', 'Puducherry', 'locality'),
  loc('Thirubuvanai',               'Puducherry', 'Puducherry', 'locality'),
  loc('Madagadipet',                'Puducherry', 'Puducherry', 'locality'),
  loc('Mannadipet',                 'Puducherry', 'Puducherry', 'locality'),
  loc('Kalapet',                    'Puducherry', 'Puducherry', 'locality'),
  loc('Kanagachettikulam',          'Puducherry', 'Puducherry', 'locality'),
  loc('Pillaichavady',              'Puducherry', 'Puducherry', 'locality'),
  loc('Kottupalayam',               'Puducherry', 'Puducherry', 'locality'),
  loc('Moolakulam',                 'Puducherry', 'Puducherry', 'locality'),
  loc('Kombakkam',                  'Puducherry', 'Puducherry', 'locality'),
  loc('Uzhavarkarai',               'Puducherry', 'Puducherry', 'locality'),
  loc('Solai Nagar',                'Puducherry', 'Puducherry', 'locality'),
  loc('Shanmuga Nagar',             'Puducherry', 'Puducherry', 'locality'),
  loc('Brindavanam',                'Puducherry', 'Puducherry', 'locality'),
  loc('Viduthalai Nagar',           'Puducherry', 'Puducherry', 'locality'),
  loc('Tagore Nagar',               'Puducherry', 'Puducherry', 'locality'),
  loc('Jeeva Nagar',                'Puducherry', 'Puducherry', 'locality'),
  loc('Periyar Nagar',              'Puducherry', 'Puducherry', 'locality'),
  loc('Rajaji Nagar',               'Puducherry', 'Puducherry', 'locality'),
  loc('Natesan Nagar',              'Puducherry', 'Puducherry', 'locality'),
  loc('Ashok Nagar',                'Puducherry', 'Puducherry', 'locality'),
  loc('Kathirkamam',                'Puducherry', 'Puducherry', 'locality'),
  loc('Ellaipillaichavady',         'Puducherry', 'Puducherry', 'locality'),
  loc('Thengaithittu',              'Puducherry', 'Puducherry', 'locality'),
  loc('Chinna Veerampattinam',      'Puducherry', 'Puducherry', 'locality'),
  loc('Auroville',                  'Puducherry', 'Puducherry', 'locality'),
  loc('ECR',                        'Puducherry', 'Puducherry', 'locality'),
  loc('East Coast Road',            'Puducherry', 'Puducherry', 'locality'),
]

// ── Priority 2: Puducherry city + district towns ──────────────────────────────
const PUDUCHERRY_CITIES: SeedLocality[] = [
  loc('Puducherry',     'Puducherry',  'Puducherry',  'city',    1275004),
  loc('Karaikal',       'Karaikal',    'Puducherry',  'town',    1267995),
  loc('Mahe',           'Mahe',        'Puducherry',  'town',    1264527),
  loc('Yanam',          'Yanam',       'Puducherry',  'town',    1253405),
  loc('Ozhukarai',      'Puducherry',  'Puducherry',  'town'),
  loc('Villupuram',     'Villupuram',  'Tamil Nadu',  'city',    1253102),
]

// ── Priority 3: Major Tamil Nadu cities ──────────────────────────────────────
const TAMIL_NADU_CITIES: SeedLocality[] = [
  loc('Chennai',          'Chennai',        'Tamil Nadu', 'city',   1264527),
  loc('Coimbatore',       'Coimbatore',     'Tamil Nadu', 'city',   1267995),
  loc('Madurai',          'Madurai',        'Tamil Nadu', 'city',   1264527),
  loc('Tiruchirappalli',  'Tiruchirappalli','Tamil Nadu', 'city',   1254163),
  loc('Salem',            'Salem',          'Tamil Nadu', 'city',   1257629),
  loc('Tirunelveli',      'Tirunelveli',    'Tamil Nadu', 'city',   1254169),
  loc('Tiruppur',         'Tiruppur',       'Tamil Nadu', 'city',   1254172),
  loc('Erode',            'Erode',          'Tamil Nadu', 'city',   1272175),
  loc('Vellore',          'Vellore',        'Tamil Nadu', 'city',   1253102),
  loc('Thoothukudi',      'Thoothukudi',    'Tamil Nadu', 'city',   1254174),
  loc('Thanjavur',        'Thanjavur',      'Tamil Nadu', 'city',   1254168),
  loc('Dindigul',         'Dindigul',       'Tamil Nadu', 'city',   1273294),
  loc('Kanchipuram',      'Kanchipuram',    'Tamil Nadu', 'city',   1267153),
  loc('Chengalpattu',     'Chengalpattu',   'Tamil Nadu', 'city',   1274746),
  loc('Cuddalore',        'Cuddalore',      'Tamil Nadu', 'city',   1273294),
  loc('Kumbakonam',       'Thanjavur',      'Tamil Nadu', 'town',   1267153),
  loc('Nagapattinam',     'Nagapattinam',   'Tamil Nadu', 'town',   1262321),
  loc('Namakkal',         'Namakkal',       'Tamil Nadu', 'town',   1262321),
  loc('Karur',            'Karur',          'Tamil Nadu', 'town',   1267153),
  loc('Hosur',            'Krishnagiri',    'Tamil Nadu', 'town',   1274746),
  loc('Krishnagiri',      'Krishnagiri',    'Tamil Nadu', 'town',   1267153),
  loc('Dharmapuri',       'Dharmapuri',     'Tamil Nadu', 'town',   1273294),
  loc('Perambalur',       'Perambalur',     'Tamil Nadu', 'town',   1262321),
  loc('Ariyalur',         'Ariyalur',       'Tamil Nadu', 'town',   1262321),
  loc('Sivaganga',        'Sivaganga',      'Tamil Nadu', 'town',   1254168),
  loc('Virudhunagar',     'Virudhunagar',   'Tamil Nadu', 'town',   1254169),
  loc('Ramanathapuram',   'Ramanathapuram', 'Tamil Nadu', 'town',   1254174),
  loc('Kanyakumari',      'Kanyakumari',    'Tamil Nadu', 'town',   1254174),
  loc('Nagercoil',        'Kanyakumari',    'Tamil Nadu', 'town',   1262321),
  // Chennai localities
  loc('T. Nagar',         'Chennai',        'Tamil Nadu', 'locality'),
  loc('Mylapore',         'Chennai',        'Tamil Nadu', 'locality'),
  loc('Velachery',        'Chennai',        'Tamil Nadu', 'locality'),
  loc('Adyar',            'Chennai',        'Tamil Nadu', 'locality'),
  loc('Tambaram',         'Chennai',        'Tamil Nadu', 'locality'),
  loc('Chromepet',        'Chennai',        'Tamil Nadu', 'locality'),
  loc('Perambur',         'Chennai',        'Tamil Nadu', 'locality'),
  loc('Ambattur',         'Chennai',        'Tamil Nadu', 'locality'),
  loc('Avadi',            'Chennai',        'Tamil Nadu', 'locality'),
  loc('Porur',            'Chennai',        'Tamil Nadu', 'locality'),
  loc('Guindy',           'Chennai',        'Tamil Nadu', 'locality'),
  loc('Kodambakkam',      'Chennai',        'Tamil Nadu', 'locality'),
  loc('Nungambakkam',     'Chennai',        'Tamil Nadu', 'locality'),
  loc('Egmore',           'Chennai',        'Tamil Nadu', 'locality'),
  loc('Royapettah',       'Chennai',        'Tamil Nadu', 'locality'),
  loc('Triplicane',       'Chennai',        'Tamil Nadu', 'locality'),
  loc('Tondiarpet',       'Chennai',        'Tamil Nadu', 'locality'),
  loc('Washermanpet',     'Chennai',        'Tamil Nadu', 'locality'),
  loc('Thiruvottiyur',    'Chennai',        'Tamil Nadu', 'locality'),
  loc('Sholinganallur',   'Chennai',        'Tamil Nadu', 'locality'),
  loc('Perungudi',        'Chennai',        'Tamil Nadu', 'locality'),
  loc('Thoraipakkam',     'Chennai',        'Tamil Nadu', 'locality'),
  loc('Pallikaranai',     'Chennai',        'Tamil Nadu', 'locality'),
  loc('Medavakkam',       'Chennai',        'Tamil Nadu', 'locality'),
  loc('Madipakkam',       'Chennai',        'Tamil Nadu', 'locality'),
  loc('Nanganallur',      'Chennai',        'Tamil Nadu', 'locality'),
  loc('Alandur',          'Chennai',        'Tamil Nadu', 'locality'),
  loc('Saidapet',         'Chennai',        'Tamil Nadu', 'locality'),
  loc('Besant Nagar',     'Chennai',        'Tamil Nadu', 'locality'),
]

// ── Priority 4: Indian cities (from cities.json reference) ──────────────────
const INDIA_CITIES: SeedLocality[] = [
  loc('Mumbai',             'Mumbai',           'Maharashtra',      'city', 1275339),
  loc('Delhi',              'New Delhi',         'Delhi',            'city', 1273294),
  loc('New Delhi',          'New Delhi',         'Delhi',            'city', 1261481),
  loc('Bengaluru',          'Bengaluru',         'Karnataka',        'city', 1277333),
  loc('Hyderabad',          'Hyderabad',         'Telangana',        'city', 1269843),
  loc('Ahmedabad',          'Ahmedabad',         'Gujarat',          'city', 1279233),
  loc('Pune',               'Pune',              'Maharashtra',      'city', 1259229),
  loc('Kolkata',            'Kolkata',           'West Bengal',      'city', 1275004),
  loc('Jaipur',             'Jaipur',            'Rajasthan',        'city', 1269515),
  loc('Lucknow',            'Lucknow',           'Uttar Pradesh',    'city', 1264527),
  loc('Kanpur',             'Kanpur',            'Uttar Pradesh',    'city', 1267995),
  loc('Nagpur',             'Nagpur',            'Maharashtra',      'city', 1262321),
  loc('Indore',             'Indore',            'Madhya Pradesh',   'city', 1269843),
  loc('Thane',              'Thane',             'Maharashtra',      'city', 1254163),
  loc('Bhopal',             'Bhopal',            'Madhya Pradesh',   'city', 1275339),
  loc('Visakhapatnam',      'Visakhapatnam',     'Andhra Pradesh',   'city', 1253102),
  loc('Pimpri-Chinchwad',   'Pune',              'Maharashtra',      'city', 1259229),
  loc('Patna',              'Patna',             'Bihar',            'city', 1260086),
  loc('Vadodara',           'Vadodara',          'Gujarat',          'city', 1253102),
  loc('Ghaziabad',          'Ghaziabad',         'Uttar Pradesh',    'city', 1273294),
  loc('Ludhiana',           'Ludhiana',          'Punjab',           'city', 1264527),
  loc('Agra',               'Agra',              'Uttar Pradesh',    'city', 1279233),
  loc('Nashik',             'Nashik',            'Maharashtra',      'city', 1262321),
  loc('Faridabad',          'Faridabad',         'Haryana',          'city', 1273294),
  loc('Meerut',             'Meerut',            'Uttar Pradesh',    'city', 1264527),
  loc('Rajkot',             'Rajkot',            'Gujarat',          'city', 1259229),
  loc('Varanasi',           'Varanasi',          'Uttar Pradesh',    'city', 1253102),
  loc('Srinagar',           'Srinagar',          'Jammu & Kashmir',  'city', 1254163),
  loc('Aurangabad',         'Aurangabad',        'Maharashtra',      'city', 1275339),
  loc('Dhanbad',            'Dhanbad',           'Jharkhand',        'city', 1273294),
  loc('Amritsar',           'Amritsar',          'Punjab',           'city', 1279233),
  loc('Navi Mumbai',        'Mumbai',            'Maharashtra',      'city', 1262321),
  loc('Allahabad',          'Prayagraj',         'Uttar Pradesh',    'city', 1264527),
  loc('Prayagraj',          'Prayagraj',         'Uttar Pradesh',    'city', 1264527),
  loc('Ranchi',             'Ranchi',            'Jharkhand',        'city', 1259229),
  loc('Howrah',             'Howrah',            'West Bengal',      'city', 1275004),
  loc('Coimbatore',         'Coimbatore',        'Tamil Nadu',       'city', 1267995),
  loc('Jabalpur',           'Jabalpur',          'Madhya Pradesh',   'city', 1269843),
  loc('Gwalior',            'Gwalior',           'Madhya Pradesh',   'city', 1254163),
  loc('Vijayawada',         'Vijayawada',        'Andhra Pradesh',   'city', 1253102),
  loc('Jodhpur',            'Jodhpur',           'Rajasthan',        'city', 1269515),
  loc('Raipur',             'Raipur',            'Chhattisgarh',     'city', 1260086),
  loc('Kochi',              'Ernakulam',         'Kerala',           'city', 1267995),
  loc('Chandigarh',         'Chandigarh',        'Chandigarh',       'city', 1273294),
  loc('Thiruvananthapuram', 'Thiruvananthapuram','Kerala',           'city', 1254163),
  loc('Kozhikode',          'Kozhikode',         'Kerala',           'city', 1267153),
  loc('Bhubaneswar',        'Khordha',           'Odisha',           'city', 1275339),
  loc('Guwahati',           'Kamrup',            'Assam',            'city', 1273294),
  loc('Gurugram',           'Gurugram',          'Haryana',          'city', 1264527),
  loc('Noida',              'Gautam Buddha Nagar','Uttar Pradesh',   'city', 1262321),
  loc('Mysuru',             'Mysuru',            'Karnataka',        'city', 1262321),
  loc('Mangaluru',          'Dakshina Kannada',  'Karnataka',        'city', 1264527),
  loc('Hubballi',           'Dharwad',           'Karnataka',        'city', 1273294),
  loc('Belagavi',           'Belagavi',          'Karnataka',        'city', 1279233),
  loc('Kalaburagi',         'Kalaburagi',        'Karnataka',        'city', 1259229),
  loc('Thrissur',           'Thrissur',          'Kerala',           'city', 1254163),
  loc('Kollam',             'Kollam',            'Kerala',           'city', 1267153),
  loc('Palakkad',           'Palakkad',          'Kerala',           'city', 1262321),
  loc('Malappuram',         'Malappuram',        'Kerala',           'city', 1264527),
  loc('Kannur',             'Kannur',            'Kerala',           'city', 1273294),
  loc('Ernakulam',          'Ernakulam',         'Kerala',           'city', 1279233),
  loc('Alappuzha',          'Alappuzha',         'Kerala',           'city', 1259229),
  loc('Kottayam',           'Kottayam',          'Kerala',           'city', 1275004),
  loc('Secunderabad',       'Hyderabad',         'Telangana',        'city', 1254163),
  loc('Warangal',           'Warangal',          'Telangana',        'city', 1253102),
  loc('Guntur',             'Guntur',            'Andhra Pradesh',   'city', 1273294),
  loc('Nellore',            'Nellore',           'Andhra Pradesh',   'city', 1262321),
  loc('Tirupati',           'Tirupati',          'Andhra Pradesh',   'city', 1264527),
  loc('Kakinada',           'East Godavari',     'Andhra Pradesh',   'city', 1267153),
  loc('Rajahmundry',        'East Godavari',     'Andhra Pradesh',   'city', 1262321),
  loc('Durgapur',           'Paschim Bardhaman', 'West Bengal',      'city', 1273294),
  loc('Asansol',            'Paschim Bardhaman', 'West Bengal',      'city', 1279233),
  loc('Surat',              'Surat',             'Gujarat',          'city', 1259229),
  loc('Bhavnagar',          'Bhavnagar',         'Gujarat',          'city', 1275004),
  loc('Jamnagar',           'Jamnagar',          'Gujarat',          'city', 1254163),
  loc('Udaipur',            'Udaipur',           'Rajasthan',        'city', 1267153),
  loc('Ajmer',              'Ajmer',             'Rajasthan',        'city', 1262321),
  loc('Kota',               'Kota',              'Rajasthan',        'city', 1264527),
  loc('Bikaner',            'Bikaner',           'Rajasthan',        'city', 1273294),
  loc('Jalandhar',          'Jalandhar',         'Punjab',           'city', 1279233),
  loc('Patiala',            'Patiala',           'Punjab',           'city', 1259229),
  loc('Ambala',             'Ambala',            'Haryana',          'city', 1275004),
  loc('Rohtak',             'Rohtak',            'Haryana',          'city', 1254163),
  loc('Jamshedpur',         'East Singhbhum',    'Jharkhand',        'city', 1267153),
  loc('Cuttack',            'Cuttack',           'Odisha',           'city', 1262321),
  loc('Rourkela',           'Sundargarh',        'Odisha',           'city', 1264527),
  loc('Dibrugarh',          'Dibrugarh',         'Assam',            'city', 1273294),
  loc('Silchar',            'Cachar',            'Assam',            'city', 1279233),
  loc('Bilaspur',           'Bilaspur',          'Chhattisgarh',     'city', 1259229),
  loc('Gaya',               'Gaya',              'Bihar',            'city', 1275004),
  loc('Dharwad',            'Dharwad',           'Karnataka',        'city', 1254163),

  // Additional cities from cities.json
  loc('Firozabad',          'Firozabad',         'Uttar Pradesh',    'city'),
  loc('Siliguri',           'Darjeeling',        'West Bengal',      'city'),
  loc('Kalyan-Dombivali',   'Thane',             'Maharashtra',      'city'),
  loc('Vasai-Virar',        'Palghar',           'Maharashtra',      'city'),
  loc('Mira-Bhayandar',     'Thane',             'Maharashtra',      'city'),
  loc('Bhiwandi',           'Thane',             'Maharashtra',      'city'),
  loc('Saharanpur',         'Saharanpur',        'Uttar Pradesh',    'city'),
  loc('Amravati',           'Amravati',          'Maharashtra',      'city'),
  loc('Bhilai Nagar',       'Durg',              'Chhattisgarh',     'city'),
  loc('Dehradun',           'Dehradun',          'Uttarakhand',      'city'),
  loc('Nanded-Waghala',     'Nanded',            'Maharashtra',      'city'),
  loc('Ujjain',             'Ujjain',            'Madhya Pradesh',   'city'),
  loc('Sangli',             'Sangli',            'Maharashtra',      'city'),
  loc('Jhansi',             'Jhansi',            'Uttar Pradesh',    'city'),
  loc('Jammu',              'Jammu',             'Jammu & Kashmir',  'city'),
  loc('Malegaon',           'Nashik',            'Maharashtra',      'city'),
  loc('Davanagere',         'Davanagere',        'Karnataka',        'city'),
  loc('Akola',              'Akola',             'Maharashtra',      'city'),
  loc('Kurnool',            'Kurnool',           'Andhra Pradesh',   'city'),
  loc('Bokaro Steel City',  'Bokaro',            'Jharkhand',        'city'),
  loc('Ballari',            'Ballari',           'Karnataka',        'city'),
  loc('Agartala',           'West Tripura',      'Tripura',          'city'),
  loc('Bhagalpur',          'Bhagalpur',         'Bihar',            'city'),
  loc('Latur',              'Latur',             'Maharashtra',      'city'),
  loc('Dhule',              'Dhule',             'Maharashtra',      'city'),
  loc('Korba',              'Korba',             'Chhattisgarh',     'city'),
  loc('Bhilwara',           'Bhilwara',          'Rajasthan',        'city'),
  loc('Brahmapur',          'Ganjam',            'Odisha',           'city'),
  loc('Muzaffarpur',        'Muzaffarpur',       'Bihar',            'city'),
  loc('Ahmednagar',         'Ahmednagar',        'Maharashtra',      'city'),
  loc('Shahjahanpur',       'Shahjahanpur',      'Uttar Pradesh',    'city'),
  loc('Alwar',              'Alwar',             'Rajasthan',        'city'),
  loc('Nizamabad',          'Nizamabad',         'Telangana',        'city'),
  loc('Sagar',              'Sagar',             'Madhya Pradesh',   'city'),
  loc('Tumkur',             'Tumkur',            'Karnataka',        'city'),
  loc('Hisar',              'Hisar',             'Haryana',          'city'),
  loc('Panipat',            'Panipat',           'Haryana',          'city'),
  loc('Darbhanga',          'Darbhanga',         'Bihar',            'city'),
  loc('Kharagpur',          'Paschim Medinipur', 'West Bengal',      'city'),
  loc('Aizawl',             'Aizawl',            'Mizoram',          'city'),
  loc('Ichalkaranji',       'Kolhapur',          'Maharashtra',      'city'),
  loc('Karnal',             'Karnal',            'Haryana',          'city'),
  loc('Bathinda',           'Bathinda',          'Punjab',           'city'),
  loc('Shivamogga',         'Shivamogga',        'Karnataka',        'city'),
  loc('Ratlam',             'Ratlam',            'Madhya Pradesh',   'city'),
  loc('Durg',               'Durg',              'Chhattisgarh',     'city'),
  loc('Shillong',           'East Khasi Hills',  'Meghalaya',        'city'),
  loc('Imphal',             'Imphal West',       'Manipur',          'city'),
  loc('Anantapur',          'Anantapur',         'Andhra Pradesh',   'city'),
  loc('Karimnagar',         'Karimnagar',        'Telangana',        'city'),
  loc('Bharatpur',          'Bharatpur',         'Rajasthan',        'city'),
  loc('Kadapa',             'Kadapa',            'Andhra Pradesh',   'city'),
  loc('Ramagundam',         'Peddapalli',        'Telangana',        'city'),
  loc('Vizianagaram',       'Vizianagaram',      'Andhra Pradesh',   'city'),
  loc('Hardwar',            'Haridwar',          'Uttarakhand',      'city'),
  loc('Haridwar',           'Haridwar',          'Uttarakhand',      'city'),
  loc('Sonipat',            'Sonipat',           'Haryana',          'city'),
  loc('Moradabad',          'Moradabad',         'Uttar Pradesh',    'city'),
  loc('Aligarh',            'Aligarh',           'Uttar Pradesh',    'city'),
  loc('Solapur',            'Solapur',           'Maharashtra',      'city'),
  loc('Amroha',             'Amroha',            'Uttar Pradesh',    'city'),
  loc('Loni',               'Ghaziabad',         'Uttar Pradesh',    'city'),
  loc('Mathura',            'Mathura',           'Uttar Pradesh',    'city'),
  loc('Shimla',             'Shimla',            'Himachal Pradesh', 'city'),
  loc('Gandhinagar',        'Gandhinagar',       'Gujarat',          'city'),
  loc('Kolhapur',           'Kolhapur',          'Maharashtra',      'city'),
  loc('Panaji',             'North Goa',         'Goa',              'city'),
  loc('Margao',             'South Goa',         'Goa',              'city'),
  loc('Rishikesh',          'Dehradun',          'Uttarakhand',      'city'),
  loc('Haldwani',           'Nainital',          'Uttarakhand',      'city'),
  loc('Mohali',             'SAS Nagar',         'Punjab',           'city'),
  loc('Panchkula',          'Panchkula',         'Haryana',          'city'),
  loc('Sambalpur',          'Sambalpur',         'Odisha',           'city'),
  loc('Khammam',            'Khammam',           'Telangana',        'city'),
  loc('Eluru',              'West Godavari',     'Andhra Pradesh',   'city'),
  loc('Porbandar',          'Porbandar',         'Gujarat',          'city'),
  loc('Anand',              'Anand',             'Gujarat',          'city'),
  loc('Nadiad',             'Kheda',             'Gujarat',          'city'),
  loc('Bharuch',            'Bharuch',           'Gujarat',          'city'),
  loc('Navsari',            'Navsari',           'Gujarat',          'city'),
  loc('Vapi',               'Valsad',            'Gujarat',          'city'),
  loc('Mahesana',           'Mahesana',          'Gujarat',          'city'),
  loc('Morvi',              'Morbi',             'Gujarat',          'city'),
  loc('Bhuj',               'Kutch',             'Gujarat',          'city'),
  loc('Pathankot',          'Pathankot',         'Punjab',           'city'),
  loc('Hoshiarpur',         'Hoshiarpur',        'Punjab',           'city'),
  loc('Zirakpur',           'SAS Nagar',         'Punjab',           'city'),
  loc('Yamunanagar',        'Yamunanagar',       'Haryana',          'city'),
  loc('Rewari',             'Rewari',            'Haryana',          'city'),
  loc('Panvel',             'Raigad',            'Maharashtra',      'city'),
  loc('Palghar',            'Palghar',           'Maharashtra',      'city'),
  loc('Ratnagiri',          'Ratnagiri',         'Maharashtra',      'city'),
  loc('Satara',             'Satara',            'Maharashtra',      'city'),
  loc('Osmanabad',          'Osmanabad',         'Maharashtra',      'city'),
  loc('Nandurbar',          'Nandurbar',         'Maharashtra',      'city'),
  loc('Wardha',             'Wardha',            'Maharashtra',      'city'),
  loc('Yavatmal',           'Yavatmal',          'Maharashtra',      'city'),
  loc('Parbhani',           'Parbhani',          'Maharashtra',      'city'),
  loc('Lonavla',            'Pune',              'Maharashtra',      'city'),
  loc('Shirdi',             'Ahmednagar',        'Maharashtra',      'city'),
  loc('Puri',               'Puri',              'Odisha',           'city'),
  loc('Sambalpur',          'Sambalpur',         'Odisha',           'city'),
  loc('Baripada',           'Mayurbhanj',        'Odisha',           'city'),
  loc('Jorhat',             'Jorhat',            'Assam',            'city'),
  loc('Tezpur',             'Sonitpur',          'Assam',            'city'),
  loc('Nagaon',             'Nagaon',            'Assam',            'city'),
  loc('Dispur',             'Kamrup',            'Assam',            'city'),
  loc('Kohima',             'Kohima',            'Nagaland',         'city'),
  loc('Dimapur',            'Dimapur',           'Nagaland',         'city'),
  loc('Aizawl',             'Aizawl',            'Mizoram',          'city'),
  loc('Kota',               'Kota',              'Rajasthan',        'city'),
  loc('Mirzapur',           'Mirzapur',          'Uttar Pradesh',    'city'),
  loc('Kullu',              'Kullu',             'Himachal Pradesh', 'city'),
  loc('Manali',             'Kullu',             'Himachal Pradesh', 'city'),
]

export const SEED_LOCALITIES: SeedLocality[] = [
  ...PONDICHERRY_LOCALITIES,
  ...PUDUCHERRY_CITIES,
  ...TAMIL_NADU_CITIES,
  ...INDIA_CITIES,
]

// Deduplicate by name_normalized
const seen = new Set<string>()
export const SEED_LOCALITIES_DEDUPED = SEED_LOCALITIES.filter(l => {
  if (seen.has(l.name_normalized)) return false
  seen.add(l.name_normalized)
  return true
})

export const SEED_ALIASES = ALIAS_MAP
